import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Playfair_Display, Dancing_Script } from "next/font/google";
import { Quintessential } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400","600","700"]
});

const dancing = Dancing_Script({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const quintessential = Quintessential({
  subsets: ["latin"],
  weight: ["400"] // this font has only one weight
});

export { quintessential };

export { playfair, dancing };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${quintessential.className}`}>
        {children}
      </body>
    </html>
  );
}
